### PR TITLE
feat: new Recipe for Butter

### PR DESCRIPTION
**Pull request by lstebner**
adds a new recipe for Butter!

Screen Shot 2021-06-06 at 6 58 56 PM
121362286-9c538d80-c8fb-11eb-95e9-7ab88ede11c3

### CODE REVIEW

**Comment by jeremyckahn** [comment]
@lstebner Nice!! Thanks for getting this recipe and its art started. I'd like to tweak the image a little bit when I can.

It looks like there's nothing in the PR diff for this — did your commits get lost with a force push?

**Comment by lstebner** [comment]
@jeremyckahn 😅 haha no, i was just moving too fast and didn't actually commit anything at all after staging. pushed now!

**Comment by jeremyckahn** [comment]
I worked on the butter art a bit! What do you think @lstebner?

butter


Screen Shot 2021-06-09 at 8 19 33 AM

**Review by jeremyckahn — APPROVED** [review]
The code looks good to me! Feel free to merge and run a `patch` release once you're happy with the art. Thanks for putting this together!

**Pull request closed without merging**
