### PR TITLE
feat: Add Pie recipe and Lord of the Pies achievement

### PR DESCRIPTION
**Pull request by jeremyckahn**
### What this PR does

This PR adds:

- A new Pumpkin Pie recipe
- A new achievement in honor of M8theone on Discord

### How this change can be validated

To learn the Pumpkin Pie recipe, sell at least:

- 200 Pumpkins
- 250 Wheat
- 75 Butter

Or run this snippet in the browser JavaScript console: 

```js
farmhand.setState({ itemsSold: { pumpkin: 200, wheat: 250, butter: 75 } })
```

And then sell any item to trigger the recipe evaluation.

To achieve the Lord of the Pies achievement, have $3,141,592 on hand (cents are ignored). You can alternatively run this snippet in the browser JavaScript console:

```js
farmhand.setState({ money: 3141592 })
```

### Additional information

Screenshot of Pumpkin Pie recipe

Screenshot of Lord of the Pies achievment

### CODE REVIEW

**Comment by lstebner** [comment]
i wanted to give the pie a little bit more shape, but i ended up altering it quite a bit, however i don't want to push to this branch without sharing for feedback so here's how it turned out:

image

**Review by lstebner — APPROVED** [review]
this change makes me want to add sweet potatoes and sweet potato pie, though i suppose we already have lots of fruits for more pie recipes! 😋

**Comment by lstebner** [comment]
i approved cause everything is working as expected and the art you made is solid, but if you like the changes i made to the art (or we want to make some more changes to mine) i can commit it

**Comment by jeremyckahn** [comment]
> if you like the changes i made to the art (or we want to make some more changes to mine) i can commit it

I like it! Feel free to push your changes and we can run with that. I might do a bit more pixel tweaking, but I like the updated aesthetic you have.

**Comment by jeremyckahn** [comment]
I added https://github.com/jeremyckahn/farmhand/pull/368/commits/6dedda74b35d43a8cda3b254e9ace4037ba8deac, which rounds out the pie art a bit more. I'm feeling pretty good about the art now, so I'll merge and ship this. Thanks the help @lstebner!

Pumpkin Pie

**Pull request merged**
