### PR TITLE
chore: move crops out of items.js

### PR DESCRIPTION
**Pull request by lstebner**
moving all crops defined in items.js into their own files inside a
  crops/ dir, containing an index. leaving the entry point for the rest
  of the app as items.js for now.

  this also adds tests and initial snapshots for all crops and seeds.

### CODE REVIEW

**Comment by lstebner** [comment]
@jeremyckahn what do you think of this reorganization? i'm ready for an official review here

**Review by jeremyckahn — CHANGES_REQUESTED** [review]
This is awesome!! Thank you for doing this. Sorry about the turnaround time for my review here, but it gets my informal approval. I'll give formal approval to merge this once conflicts have been resolved and it's been updated to include Asparagus.

Great work so far!!

**Comment by lstebner** [comment]
> This is awesome!! Thank you for doing this. Sorry about the turnaround time for my review here, but it gets my informal approval. I'll give formal approval to merge this once conflicts have been resolved and it's been updated to include Asparagus.
> 
> Great work so far!!

thank you, will get this updated for asparagus soon!

**Comment by lstebner** [comment]
updated to include asparagus and jalapeno @jeremyckahn . i'm a little anxious to get this merged now because i more or less had to recreate it, and i know we've got more crops in other PRs already 😅 .

**Review by jeremyckahn — APPROVED** [review]
LGTM, let's ship it! Thanks for making this huge organizational improvement! 🎉

**Pull request merged**
