### PR TITLE
feat: [closes #120] new jalapeno recipes

### LINKED ISSUE #120: add Jalapeño recipes
I thought of 3 recipes to add around the new crop.

1. Hot Sauce; ingredients- 10 jalapeño; unlocks after selling 50 jalapeño
2. Salsa; ingredients- 1 jalapeño, 1 onion, 1 tomato, 1 corn; unlocks after selling 5x of each ingredient
3. Spicy Cheese; ingredients 4 jalapeño, 1 cheese; unlocks after selling 20 jalapeño and 5 chees

### PR DESCRIPTION
**Pull request by lstebner**
new recipes include:
  - Hot Sauce
  - Spicy Cheese
  - Salsa

Screen Shot 2021-06-26 at 2 16 18 PM
Screen Shot 2021-06-27 at 10 25 10 AM
Screen Shot 2021-06-26 at 2 24 44 PM

### CODE REVIEW

**Comment by lstebner** [comment]
i came up with two hot sauce bottle ideas (just the label is different), but of course you can rework this as much as you want @jeremyckahn . just wanted to call out i added 2, but only plan on using 1, so we can delete the other once we choose

hot-sauce-b
hot-sauce

**Comment by jeremyckahn** [comment]
> i came up with two hot sauce bottle ideas (just the label is different), but of course you can rework this as much as you want @jeremyckahn . just wanted to call out i added 2, but only plan on using 1, so we can delete the other once we choose

I really like these! Between the two variants, I think `hot-sauce.png` works a little better visually given how it's presented in the game's UI. These images are pretty small and the little Jalapeño on the label stands out better. I'll make a few minor adjustments and push them to this PR soon!

**Comment by jeremyckahn** [comment]
I just pushed a few very minor tweaks to `hot-sauce`:

Screen Shot 2021-06-19 at 12 07 24 PM

I also deleted `hot-sauce-b` for you, but it's in the Git history in case we want to resurrect it later. Really good progress with these so far! 🤠

**Comment by lstebner** [comment]
thanks for updating hot sauce @jeremyckahn ! i added some art for the other 2 recipes you can feel free to touch up all you want. while i was making those, i was having second thoughts about the ingredients for "spicy cheese". i used the other cheese wedge as a starting point and added pepper into it, maybe the recipe should be the same as cheese + jalapeño, instead of requiring a cheese be made first. what do you think?

**Comment by jeremyckahn** [comment]
Awesome, I'll work on the new art next! Thanks for getting it started.

>  i used the other cheese wedge as a starting point and added pepper into it, maybe the recipe should be the same as cheese + jalapeño, instead of requiring a cheese be made first. what do you think?

I'm not quite following here — are you suggesting that we change the recipe from Spicy Cheese to be Grade A Milk + Jalapeño?

**Comment by lstebner** [comment]
> I'm not quite following here — are you suggesting that we change the recipe from Spicy Cheese to be Grade A Milk + Jalapeño?

oops, yeah i see now re-reading my message it was very confusing! i implemented the current recipe for spicy cheese as "cheese + jalapeño", but now i'm thinking it should be the same as the cheese recipe, but with added jalapeño instead of using a premade cheese. so like, "8 grade A milk + jalapeño" to make spicy cheese. hopefully that makes sense now @jeremyckahn but hit me up in discord if not

**Comment by jeremyckahn** [comment]
>i implemented the current recipe for spicy cheese as "cheese + jalapeño", but now i'm thinking it should be the same as the cheese recipe, but with added jalapeño instead of using a premade cheese. so like, "8 grade A milk + jalapeño" to make spicy cheese.

Ah yeah, that makes sense to me! I think the new recipe idea is a little bit closer to how spicy cheese might work in real life. Let's go with that!

**Comment by jeremyckahn** [comment]
I just pushed up some tweaks for Spicy Cheese and Salsa! What do you think @lstebner?

Screen Shot 2021-06-27 at 8 45 47 PM

**Comment by lstebner** [comment]
looking great @jeremyckahn ! i updated the recipe, and i'm good with everything as it is now. ready for an official review i believe

**Review by jeremyckahn — APPROVED** [review]
This all looks great to me! Thanks for coming up with and implementing all these new recipes. I'll let you merge this into `lstebner/feature-jalapeno` and then that branch to `develop` for a `patch` release whenever you're ready. Good idea to ship this all together — I think it'll be a spicy update for players! 🌶

Screen Shot 2021-06-28 at 7 59 06 AM

**Pull request merged**
