### PR TITLE
[closes #27] refactor: using floor instead of round

### LINKED ISSUE #27: Lotta Saloks
So I was curious how reliable Math.random() * list.length was after four of my 30 cows were named "Salak" and four were named "Sapote" and wrote up this janky script in the console. 

```
a = new Array(100); for (i=0;i<100000;i++) { v = Math.round(Math.random() * (a.length - 1)); a[v] = parseInt(a[v]) + 1 || 0 + 1; }; a.map((value, count) => `${count}:${value}`);
```

Turns out you get a similar distribution over many iterations, with some numbers appearing less frequently than others, especially on the extremes. 

```
["0:521", "1:1002", "2:1003", "3:939", "4:1069", "5:945", "6:1037", "7:1035", "8:1035", "9:944", "10:943", "11:995", "12:1009", "13:1021", "14:1036", "15:1051", "16:1022", "17:987", "18:959", "19:1003", "20:961", "21:957", "22:957", "23:1053", "24:962", "25:1013", "26:1045", "27:1007", "28:974", "29:1020", "30:977", "31:1004", "32:1057", "33:1016", "34:990", "35:1000", "36:1002", "37:990", "38:1030", "39:1093", "40:1006", "41:1012", "42:1003", "43:1042", "44:1061", "45:1005", "46:1073", "47:965", "48:1020", "49:957", "50:1078", "51:960", "52:1004", "53:1062", "54:957", "55:950", "56:1044", "57:990", "58:1024", "59:1054", "60:976", "61:1020", "62:994", "63:1058", "64:991", "65:1063", "66:1014", "67:1000", "68:984", "69:1043", "70:983", "71:976", "72:1010", "73:1057", "74:1039", "75:1030", "76:1031", "77:1013", "78:1067", "79:984", "80:1010", "81:996", "82:1037", "83:961", "84:1023", "85:1060", "86:988", "87:1065", "88:995", "89:996", "90:1018", "91:1074", "92:957", "93:969", "94:1023", "95:1013", "96:1002", "97:1039", "98:1007", "99:503"]
```

But what you if you run it twice, and look at the decimal on the float as a source of increased entropy by multiplying by a large power of 10 to turn them into large integers so you can get a modulus? Whoa ~nelly~ salak that sounds random!

```
rand = (min, max) => (Math.floor(Math.pow(10,14)*Math.random()*Math.random())%(max-min+1))+min;
a = new Array(100); for (i=0;i<100000;i++) { v = rand(0, a.length - 1); a[v] = parseInt(a[v]) + 1 || 0 + 1; }; a.map((value, count) => `${count}:${value}`);
```

```
["0:1003", "1:1050", "2:1012", "3:1069", "4:969", "5:938", "6:990", "7:1019", "8:1042", "9:970", "10:981", "11:966", "12:961", "13:1026", "14:977", "15:987", "16:1024", "17:981", "18:994", "19:980", "20:986", "21:1016", "22:926", "23:1020", "24:1023", "25:1039", "26:1000", "27:1032", "28:1023", "29:990", "30:977", "31:1004", "32:994", "33:978", "34:1049", "35:936", "36:966", "37:1003", "38:1004", "39:1025", "40:983", "41:960", "42:1025", "43:1036", "44:1031", "45:990", "46:1019", "47:991", "48:954", "49:1021", "50:1000", "51:951", "52:1046", "53:959", "54:1001", "55:1012", "56:994", "57:954", "58:1050", "59:1026", "60:989", "61:933", "62:930", "63:985", "64:1002", "65:1052", "66:1014", "67:1044", "68:1073", "69:982", "70:935", "71:983", "72:1048", "73:1002", "74:980", "75:994", "76:1014", "77:956", "78:980", "79:1033", "80:1055", "81:1008", "82:1042", "83:1070", "84:996", "85:985", "86:1012", "87:1019", "88:976", "89:968", "90:1009", "91:1010", "92:970", "93:1018", "94:1003", "95:997", "96:997", "97:995", "98:1012", "99:996"]
```

Ahh. That's more like it.

### PR DESCRIPTION
**Pull request by lstebner**
when choosing a random item from the list, use Math.floor and multiply
  by the list length to produce more evenly dispersed results.

### CODE REVIEW

**Comment by lstebner** [comment]
will look into why test and build failed when i get a chance this evening

**Comment by jeremyckahn** [comment]
> will look into why test and build failed when i get a chance this evening

I think the way `Math.random` is mocked out for this test might need to be revisited: https://github.com/jeremyckahn/farmhand/blob/1462ca1f755ba3ab320ff388b1917b4043550372/src/utils.test.js#L210-L227

**Comment by jeremyckahn** [comment]
Oh actually I think it's because with the new algorithm, the last item the in the array can never be selected. 😬

**Comment by lstebner** [comment]
oops, fixed that 😄

**Comment by lstebner** [comment]
after talking about this more with @jeremyckahn we're actually going to just close this PR and not implement this. there is a bit of a bias with the way `Math.random` is being used here, but adding in `floor` will actually make the bias worse. we could look into solving this more specific to how names are generated/fetched, or by getting an external library that is better at producing evenly dispersed results.

**Pull request closed without merging**
