### PR TITLE
[closes #87] feat: new recipe Summer Salad

### LINKED ISSUE #87: Spinach Salad
add new recipe: Spinach salad. i want to look into how recipes work, so i'm not sure what other details need added here. but i think after selling some spinach the player should learn to make spinach salad

### PR DESCRIPTION
**Pull request by lstebner**
adds a new recipe for making a Summer Salad. 

## recipe details

- unlocks after the player has sold at least 30 Spinach, 5 Corn, and 5 Carrots
- requires 6 spinach, 1 corn, and 1 carrot to prepare

because of the corn requirement, this recipe will unlock after level 10 for most players. 

## images

summer-salad
Screen Shot 2021-06-05 at 10 25 10 AM
Screen Shot 2021-06-05 at 10 25 22 AM
Screen Shot 2021-06-05 at 10 25 34 AM
Screen Shot 2021-06-05 at 10 25 41 AM

### CODE REVIEW

**Comment by lstebner** [comment]
@jeremyckahn pinging you an art request for this 😄

**Comment by jeremyckahn** [comment]
@lstebner I added some art for this! I was thinking we might want to tweak a few things here before merging. I'd like to change the ingredients to include Corn and Carrots, and possibly consider changing the name to something a little more general like "Basic Salad" so we could add logical tiers of salads down the road. What do you think?

Screen Shot 2021-06-04 at 8 26 10 PM

**Comment by lstebner** [comment]
nice! so how does 6 spinach + 1 corn + 1 carrot sound for the recipe? and what if we called it something like "Chopped Spinach Salad" or "Summer Salad"? I definitely would like to name it so we can have more salads down the road, i imagine we'll have other types of greens too which will assist with naming when the time comes.

**Comment by jeremyckahn** [comment]
>so how does 6 spinach + 1 corn + 1 carrot sound for the recipe?

That sounds good to me! 👍 

>what if we called it something like "Chopped Spinach Salad" or "Summer Salad"?

I like Summer Salad a lot. Let's go with that!

**Comment by lstebner** [comment]
how do you feel about the unlock conditions for this one @jeremyckahn ? it was "sell 20 spinach", but i'm adding to it additionally "sell 20 corn". does that seem ok?

**Comment by jeremyckahn** [comment]
> how do you feel about the unlock conditions for this one @jeremyckahn ? it was "sell 20 spinach", but i'm adding to it additionally "sell 20 corn". does that seem ok?

I've been trying to keep the unlock conditions for recipes roughly reflective of the proportionality of their ingredients. So in the case of this salad, (in my mind) there's a lot more spinach than corn and carrots, so it should therefore require a greater amount of spinach than corn/carrots to unlock. So for instance, requiring 20 spinaches, 5-10 corns, and 5-10 carrots would be roughly consistent with the other recipes.

**Comment by lstebner** [comment]
alright @jeremyckahn i think this is in good shape for an official final review!

**Review by jeremyckahn — APPROVED** [review]
This looks great! Thanks for adding this. Let's wait for this to be successfully deployed to the preview environment and pass all the checks, and I'm good with merging and making a `patch` release!

**Pull request merged**
